---
ghc-build: standard
templates:
  params:
    author-email: pbrisbin@gmail.com
    author-name: Patrick Brisbin
    category: Network
    copyright: 2017 Patrick Brisbin
    github-username: pbrisbin
  scm-init: git
save-hackage-creds: true
